apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cm1
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        jsonData:
          httpMethod: POST
          timeInterval: 5s
        isDefault: true
        editable: true