apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-data
  labels:
    io.kompose.service: user-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi 