apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: ycsb-results
  name: ycsb-results
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: ycsb-interface
  name: ycsb-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ycsb-interface
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: ycsb-interface
    spec:
      containers:
        - image: <repo>/<project_id>/<repo_name>/<image_name>:<tag>
          name: ycsb-interface
          ports:
            - containerPort: 8000
              protocol: TCP
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /results
              name: ycsb-results
      restartPolicy: Always
      volumes:
        - name: ycsb-results
          persistentVolumeClaim:
            claimName: ycsb-results
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: ycsb-interface
  name: ycsb-interface
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    io.kompose.service: ycsb-interface
