apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: mysql-ycsb-interface
  name: mysql-ycsb-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-ycsb-interface
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: mysql-ycsb-interface
    spec:
      containers:
        - args:
            - /bin/bash
          image: <repo>/<project_id>/<repo_name>/<image_name>:<tag>
          name: mysql-ycsb-interface
          ports:
            - containerPort: 3306
              protocol: TCP
          stdin: true
          tty: true
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mysql-ycsb-interface
  name: mysql-ycsb-interface
spec:
  selector:
    io.kompose.service: mysql-ycsb-interface
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
    - name: mysql-alt
      port: 3308
      targetPort: 3308
      protocol: TCP
